site_name: língua Panglo
site_url: https://www.pandunia.info/panglo/por
repo_url: https://github.com/barumau/PanGlobish/
docs_dir: ../../por
site_dir: ../../html/por
use_directory_urls: false
theme:
  name: material
  language: pt
  logo: logo.png
  favicon: favicon.png
extra_css:
  - stile.css
nav:
    - 'Ortografía': G-ABC.md
    - 'Pronomes': G-PRO.md
    - 'Frases básicas': B03_baze_jumla.md
    - 'Números': G-NUM.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=3
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/panglobish/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/panglobish
markdown_extensions:
  - toc:
      toc_depth: 2
