site_name: Panglo
site_url: http://www.pandunia.info/panglo/esperanto
repo_url: https://github.com/barumau/PanGlobish/
site_author: Risto Kupsala
docs_dir: ../../epo
site_dir: ../../html/epo
theme: material
extra_css:
    - extra.css
nav:
    - 'Gramatiko':
        - 'La 10 reguloj': G-baze.md
#        - 'Mondaj vortoj': L-lexe.md
#        - 'Prononcado kaj skribado': G-ABC.md
#        - 'Laŭregula akcento': 103_aksente.md
#        - Substantivoj : G-N.md
        - Nombrovortoj: G-NUM.md
        - Pronomoj: G-PRO.md
#        - Verboj: G-V.md
#        - Vortfarado: G-AFX.md
#    - Lecionoj:
#        - '1a leciono': 201_lecion_1.md
#    - 'Pri Panglo':
#        - 'La ideo': I-idea.md
#        - 'Panglo kontraŭ la angla': I_Panglo_vs_English.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=3
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/panglobish/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/panglobish
markdown_extensions:
  - toc:
      toc_depth: 2
