site_name: PanGlobish
site_url: http://www.kupsala.net/PanGlobish/english
repo_url: https://github.com/barumau/PanGlobish/
site_author: Risto "Rippe" Kupsala
docs_dir: ../../english
site_dir: ../../html/english
theme: readthedocs
nav:
    - Home: 'index.md'
    - 'Grammar and Rules':
        - 'The 10 rules': 100_baze_regule.md
        - 'World Words': 101_dunia_worde.md
        - 'Spelling and pronunciation': 102_ortografie.md
        - 'Regular Accent': 103_aksente.md
        - Nouns : 104_nome.md
        - Numerals: 105_numbe.md
        - Modifiers: 106_modife.md
        - Pronouns: 107_pronome.md
        - Verbs: 108_verbe.md
        - 'Sentence Structure': 109_worde_orde.md
        - 'Word building': 110_worde_kostruktion.md
    - Lessons:
        - 'Lesson 1': 201_lecion_1.md
        - 'Lesson 2': 202_lecion_2.md
    - 'About PanGlobish':
        - 'The idea': 301_idea_of_Panglobish.md
        - 'PanGlobish vs English': 302_Panglobish_vs_English.md
    - Dictionaries:
        - "PanGlobish–English" : PanGlobish-English.md
        - "English–PanGlobish" : English-PanGlobish.md

