site_name: Panglo
site_url: https://www.pandunia.info/panglo/english
repo_url: https://github.com/barumau/PanGlobish/
site_author: Risto Kupsala
docs_dir: ../../eng
site_dir: ../../html/eng
theme: material
extra_css:
    - extra.css
nav:
    - 'Grammar':
        - 'The 10 rules': G-baze.md
        - 'World Words': L-lexe.md
        - 'Spelling and pronunciation': G-ABC.md
        - 'Regular Accent': 103_aksente.md
        - Nouns : G-N.md
        - Numerals: G-NUM.md
        - Modifiers: G-ADJ.md
        - Pronouns: G-PRO.md
        - Verbs: G-V.md
        - 'Sentence Structure': 109_lexe_orde.md
        - 'Word building': G-AFX.md
    - Lessons:
        - 'Lesson 1': 201_lecion_1.md
        - 'Lesson 2': 202_lecion_2.md
    - 'About':
        - 'The idea': I-idea.md
        - 'Panglo vs English': I_Panglo_vs_English.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=3
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/panglobish/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/panglobish
markdown_extensions:
  - toc:
      toc_depth: 2

