site_name: idioma Panglo
site_url: https://www.pandunia.info/panglo/spa
repo_url: https://github.com/barumau/PanGlobish/
site_author: Risto Kupsala
docs_dir: ../../spa
site_dir: ../../html/spa
use_directory_urls: false
theme:
  name: material
  language: es
  logo: logo.png
  favicon: favicon.png
extra_css:
  - stile.css
nav:
    - Inicio: 'index.md'
    - 'Info':
        - I-filosofia.md
    - 'Gramatica':
        - G-baze.md
        - G-ABC.md
        - G-PoS.md
        - G-PRO.md
        - G-N.md
        - G-NUM.md
        - G-ADJ.md
        - G-V.md
        - G-P.md
        - G-AFX.md
    - 'Lecciones':
        - 'Frases b√°sicas': B03_baze_jumla.md
        - 'Curso': K-kurse.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=3
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/panglobish/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/panglobish
markdown_extensions:
  - toc:
      toc_depth: 2
