site_name: Panglobish
site_url: http://www.kupsala.net/PanGlobish/suomi
repo_url: https://github.com/barumau/PanGlobish/
site_author: Risto "Rippe" Kupsala
docs_dir: ../../Suomi
site_dir: ../../html/suomi
theme: readthedocs
nav:
    - Kotisivu: 'index.md'
    - 'Kielioppi':
        - '10 sääntöä': 100_baze_regule.md
        - 'Kansainväliset sanat': 101_dunia_worde.md
        - 'Kirjoitus ja ääntäminen': 102_ortografie.md
        - 'Sanojen painotus': 103_aksente.md
        - Substantiivit : 104_nome.md
        - Lukusanat: 105_numbe.md
        - Pronominit: 107_pronome.md
        - Verbit: 108_verbe.md
        - 'Sanojen johtaminen': 110_worde_kostruktion.md
    - Oppitunteja:
        - '1. oppitunti': 201_lecion_1.md
    - 'Taustatietoja':
        - 'Idea': 301_idea_of_Panglobish.md
        - 'Panglobish vs. englanti': 302_Panglobish_vs_English.md
    - Sanasto:
        - "Panglobish–suomi" : Panglobish-Suomi.md
        - "Suomi–panglobish" : Suomi-Panglobish.md
