site_name: Panglo
site_url: https://www.pandunia.info/panglo/tha
repo_url: https://github.com/barumau/PanGlobish/
docs_dir: ../../tha
site_dir: ../../html/tha
theme: material
nav:
    - Home: 'index.md'
    - 'กฎ 10 ข้อของ Panglo': G-baze.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=3
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/panglobish/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/panglobish
