site_name: PanGlobish
site_url: http://www.kupsala.net/PanGlobish/esperanto
repo_url: https://github.com/barumau/PanGlobish/
site_author: Risto "Rippe" Kupsala
docs_dir: ../../esperanto
site_dir: ../../html/esperanto
theme: readthedocs
nav:
    - Hejmpaĝo: 'index.md'
    - 'Gramatiko':
        - 'La 10 reguloj': 100_baze_regule.md
        - 'Mondaj vortoj': 101_dunia_worde.md
        - 'Prononcado kaj skribado': 102_ortografie.md
        - 'Laŭregula akcento': 103_aksente.md
        - Substantivoj : 104_nome.md
        - Nombrovortoj: 105_numbe.md
        - Pronomoj: 107_pronome.md
        - Verboj: 108_verbe.md
        - Vortfarado: 110_worde_kostruktion.md
    - Lecionoj:
        - '1a leciono': 201_lecion_1.md
    - 'Pri Duniŝo':
        - 'La ideo': 301_idea_of_Panglobish.md
        - 'Duniŝo kontraŭ la angla': 302_Panglobish_vs_English.md
    - Vortaro:
        - "Duniŝo–Esperanto" : PanGlobish-Esperanto.md
        - "Esperanto–Duniŝo" : Esperanto-PanGlobish.md
