site_name: lingua Panglo
site_url: https://www.pandunia.info/panglo/ita
repo_url: https://github.com/barumau/PanGlobish/
docs_dir: ../../ita
site_dir: ../../html/ita
use_directory_urls: false
theme:
  name: material
  language: it
  logo: logo.png
  favicon: favicon.png
extra_css:
  - stile.css
nav:
    - 'Lingua ausiliaria globale': I-idea.md
    - I-filosofia.md
    - I-suma.md
    - 'Regole basilari': G-baze.md
    - 'Ortografia e pronuncia': G-ABC.md
    - 'Classi di parole': G-PoS.md
    - 'Pronomi': G-PRO.md
    - 'Sostantivi': G-N.md
    - 'Numerali': G-NUM.md
    - 'Modificatori': G-ADJ.md
    - 'Verbi': G-V.md
    - 'Da dove vengono le parole': L-lexe.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=3
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/panglobish/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/panglobish
markdown_extensions:
  - toc:
      toc_depth: 2
