site_name: Panglo
site_url: https://www.pandunia.info/panglo/fin
repo_url: https://github.com/barumau/PanGlobish/
site_author: Risto Kupsala
docs_dir: ../../fin
site_dir: ../../html/fin
theme: material
extra_css:
    - extra.css
nav:
    - 'Kielioppi':
        - '10 sääntöä': G-baze.md
        - 'Kansainväliset sanat': L-lexe.md
        - 'Kirjoitus ja ääntäminen': G-ABC.md
        - 'Sanojen painotus': 103_aksente.md
        - Substantiivit : G-N.md
        - Lukusanat: G-NUM.md
        - Pronominit: G-PRO.md
        - Verbit: G-V.md
        - 'Sanojen johtaminen': G-AFX.md
    - Oppitunteja:
        - 'Lauseita': K-fraze.md
        - '1. oppitunti': 201_lecion_1.md
    - 'Taustatietoja':
        - 'Idea': I-idea.md
        - 'Panglo vs. englanti': I_Panglo_vs_English.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=3
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/panglobish/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/panglobish
markdown_extensions:
  - toc:
      toc_depth: 2
